FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

# Enable universe/multiverse and update
RUN sed -i '/^deb / s/$/ universe multiverse/' /etc/apt/sources.list && \
    apt-get update && \
    apt-get upgrade -y

# Install all core packages
RUN apt-get install -y \
    vim wget curl htop \
    docker.io python3 python3-pip \
    nmap whois dnsmap gdb gcc g++ bind9-dnsutils \
    net-tools iproute2 telnet john \
    openssh-client openssh-server nikto \
    netcat-openbsd strace ltrace \
    binutils bsdmainutils xxd tar \
    wireshark cron hydra git bash-completion \
    tmux zsh shellcheck jq \
    ripgrep fd-find exa bat \
    ncdu lsof psmisc mtr-tiny \
    tree silversearcher-ag unzip rclone \
    inxi neofetch progress apt-file \
    build-essential cmake ninja-build \
    libssl-dev libffi-dev zlib1g-dev \
    python3-venv python3-dev nodejs npm \
    default-jdk golang rustc cargo \
    sqlite3 postgresql-client redis-tools \
    docker-compose podman \
    awscli tcpdump iperf3 socat ngrep \
    iputils-ping sshfs openssl \
    openvpn wireguard-tools \
    smartmontools lm-sensors dmidecode \
    hdparm testdisk foremost

# Configure user environment
RUN useradd -m -s /bin/bash dev_user && \
    usermod -aG docker dev_user

USER dev_user
WORKDIR /home/dev_user

CMD ["bash"]
