#!/bin/bash

docker run -it --rm --cap-add=NET_ADMIN -d \
              -v /home/vsdev/transmission/:/data \
              -v /home/vsdev/transmission/:/config \
              -e OPENVPN_PROVIDER=SURFSHARK \
              -e OPENVPN_CONFIG=ro-buc.prod.surfshark.com_udp \
              -e OPENVPN_USERNAME=********************* \
              -e OPENVPN_PASSWORD=********************* \
              -e LOCAL_NETWORK=192.168.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn
